### ISSUE TITLE
sch_def_schtbl.tbl not being defined

### ISSUE THREAD

**Issue by PaulaBosca** [nasa/SCH#7]
SCH app fails on cFS startup as it is unable to open file. 
Errors: 
Error (RC=0xCC00002C) Loading SDT with /cf/apps/sch_def_schtbl.tbl

The app is loaded and created fine, but exits when it is unable to load this table. I've tried using commits from other errors but none seem to be working. 
New to cfs, any help is appreciated.

**Comment by skliper** [comment]
Hi @PaulaBosca, this is a NASA project correct?  Would you like to coordinate targeted support w/ cFS management?  Maybe @astrogeco could help?  You'd likely have much better luck with full access to the internal team and resources.  I know we've got SCH working internally, but the open source release is held up in the approval cycle.

**Comment by jphickey** [comment]
FYI - all the error codes (e.g. 0xCC00002C) are in the file `cfe_error.h`.  That one corresponds to `CFE_TBL_ERR_ACCESS`, which is returned when TBL is unable to open the file.  

During early development I do strongly recommend setting `OSAL_CONFIG_DEBUG_PRINTF` in your OSAL configuration if not already set.  If set, it should have generated a debug message with the actual OS error that occurred when opening the file.

Most likely you are just looking at a pathname mismatch - the file attempting to be opened is `/cf/apps/sch_def_schtbl.tbl` but the file is (probably?) installed as `/cf/sch_def_schtbl.tbl` (i.e. no /apps).

Edit - corrected the config option for debug printf, copy and pasted the wrong one... although I do recommend setting OSAL_CONFIG_DEBUG_PERMISSIVE_MODE too, it should be set by default.

**Comment by PaulaBosca** [comment]
> Hi @PaulaBosca, this is a NASA project correct? Would you like to coordinate targeted support w/ cFS management? Maybe @astrogeco could help? You'd likely have much better luck with full access to the internal team and resources. I know we've got SCH working internally, but the open source release is held up in the approval cycle.

Unfortunately I'm not working on a NASA project (hopefully some day!). This is for a Canadian CubeSat Project. 

> FYI - all the error codes (e.g. 0xCC00002C) are in the file `cfe_error.h`. That one corresponds to `CFE_TBL_ERR_ACCESS`, which is returned when TBL is unable to open the file.
> 
> During early development I do strongly recommend setting `OSAL_CONFIG_DEBUG_PRINTF` in your OSAL configuration if not already set. If set, it should have generated a debug message with the actual OS error that occurred when opening the file.
> 
> Most likely you are just looking at a pathname mismatch - the file attempting to be opened is `/cf/apps/sch_def_schtbl.tbl` but the file is (probably?) installed as `/cf/sch_def_schtbl.tbl` (i.e. no /apps).
> 
> Edit - corrected the config option for debug printf, copy and pasted the wrong one... although I do recommend setting OSAL_CONFIG_DEBUG_PERMISSIVE_MODE too, it should be set by default.

Thanks for the recommendation! I didn't know that was an option to set. Is it simply a parameter when building/making the system or does a specific file have to be edited? 
Also, I see the .tbl in the build and you're right, they were in /cf/sch_def_schtbl.tbl. I can manually move them but I'd prefer editing the file placing them in the wrong directory (or the file that looks in cf/apps rather than cf/). I noticed it doesn't seem to be in the sch/for_build/schtables.mak file. Is it in the CFE somewhere?

**Comment by jphickey** [comment]
> Also, I see the .tbl in the build and you're right, they were in /cf/sch_def_schtbl.tbl. I can manually move them but I'd prefer editing the file placing them in the wrong directory (or the file that looks in cf/apps rather than cf/). I noticed it doesn't seem to be in the sch/for_build/schtables.mak file. Is it in the CFE somewhere?

Each app does this differently, but most have some sort of "platform config" file to configure this type of thing.  For the SCH app check the `sch_platform_cfg.h` file.  I believe the filenames it tries to load are `#define`'d here in this file, you can change this to your needs.

Unfortunately some CFS apps are distributed with different defaults than CFE for the pathnames (e.g. /cf/apps vs. /cf).  Hopefully this can be ironed out in future releases of the apps.  But in the meantime if you just configure everything to match it should work.

**Comment by PaulaBosca** [comment]
Found it, it's now up and running. Thanks so much for your help!
